#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 18 07:42:11 2022

@author: edgartarraga
"""

import cv2
import numpy as np
import os

faceClassif = cv2.CascadeClassifier(cv2.data.haarcascades +"haarcascade_frontalface_default.xml")
captura = cv2.VideoCapture(0)

while True:
    ret,Cuadro = captura.read()
    if ret == True: ## Si hay imagen se  continua
        Filas,Columnas,Canales=Cuadro.shape
        Min_SizeFila=round(0.2*Filas)
        Min_SizeCol=round(0.2*Columnas)
        Max_SizeFila=round(0.6*Filas)
        Max_SizeCol=round(0.6*Columnas)
        gray = cv2.cvtColor(Cuadro, cv2.COLOR_BGR2GRAY)
        faces = faceClassif.detectMultiScale(gray,1.2,5)
        ##                
        for (x,y,w,h) in faces:
                x0=x # Coordenada inicial de las columnas 
                y0=y # Coordenada inicial de las Filas
                x1=x+w
                y1=y+h
                cv2.rectangle(Cuadro,(x0,y0),(x1,y1),(0,200,0),2)
                cv2.imshow('Cuadro',Cuadro)
        if cv2.waitKey(1) & 0xFF == ord('q'): ###Si tecla ccionada es q quit termina
            cv2.destroyAllWindows()
            cv2.waitKey(1) # Espera cierre de pantalla
            break
captura.release()                