#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Sep 18 07:42:11 2022

@author: edgartarraga
"""

import cv2
import numpy as np

faceClassif = cv2.CascadeClassifier(cv2.data.haarcascades +"haarcascade_frontalface_default.xml")
captura = cv2.VideoCapture(0)
## Cordenadas del recuadro
x0=y0=x1=y1=0
## Rangos del blanco
BlancoBajo = np.array([0, 0, 0], np.uint8)
BlancoAlto = np.array([255, 15, 255], np.uint8)
while True:
    ret,Cuadro = captura.read()
    if ret == True: ## Si hay imagen se  continua
        Filas,Columnas,Canales=Cuadro.shape
        Min_SizeFila=round(0.2*Filas)
        Min_SizeCol=round(0.2*Columnas)
        Max_SizeFila=round(0.6*Filas)
        Max_SizeCol=round(0.6*Columnas)
        gray = cv2.cvtColor(Cuadro, cv2.COLOR_BGR2GRAY)
        faces = faceClassif.detectMultiScale(gray,1.2,5)
        ##                
        for (x0,y0,w,h) in faces:
                x1=x0+w
                y1=y0+h
                cv2.rectangle(Cuadro,(x0,y0),(x1,y1),(0,200,0),3)
                y1=round(y0+h/2)
                cv2.rectangle(Cuadro,(x0,y0),(x1,y1),(0,50,0),2)
                cv2.imshow('Cuadro',Cuadro)
        ###
        recuadro=Cuadro[y0:y1,x0:x1] 
        cv2.imshow('Re-Cuadro',recuadro)
        if cv2.waitKey(1) & 0xFF == ord('q'): ###Si tecla ccionada es q quit termina
            cv2.destroyAllWindows()
            cv2.waitKey(1) # Espera cierre de pantalla
            break
captura.release()                